"""
Report parser utility for extracting structured sections from raw report text generated by the model.
This utility uses regular expressions to identify and separate different sections of the report, such 
as detection summary, standards interpretation, technical risk, recommendation, and grounding 
disclaimer. The parsed sections are returned in a structured format for further processing or 
presentation.
"""
import re


def parse_report_sections(raw_text: str) -> dict:
    """
    Parse the raw report text to extract structured sections based on predefined patterns.
    """
    section_patterns = {
        "detection_summary": r"Detection Summary:\s*(.*?)(?=Standards-Based Assessment:|$)",
        "standards_interpretation": r"Standards-Based Assessment:\s*(.*?)(?=Technical Risk / Implication:|$)",
        "technical_risk": r"Technical Risk / Implication:\s*(.*?)(?=Preliminary Disposition / Recommendation:|$)",
        "recommendation": r"Preliminary Disposition / Recommendation:\s*(.*?)(?=Limitations / Grounding Note:|$)",
        "grounding_disclaimer": r"Limitations / Grounding Note:\s*(.*)$",
    }

    parsed = {}
    for key, pattern in section_patterns.items():
        match = re.search(pattern, raw_text, re.DOTALL | re.IGNORECASE)
        parsed[key] = match.group(1).strip() if match else ""

    return parsed
