"""
Debug schema for RAG endpoint responses, providing detailed information about 
the query processing, retrieved chunks, generated answer, and timings for 
each step of the process. This schema is useful for debugging and analyzing 
the performance of the RAG system.
"""
from pydantic import BaseModel
from app.domain.schemas.common import RetrievedChunk


class DebugResponse(BaseModel):
    """
    Debug response schema for RAG endpoint
        - query: The original query string
        - prompt_used: The final prompt sent to the language model after processing
        - retrieved_chunks: A list of retrieved chunks that were relevant to the query
        - final_context: The final context constructed from the retrieved chunks and 
            any additional information
        - generated_answer: The answer generated by the language model based on the final context
        - timings_ms: A dictionary containing the timings for each step of the 
            query processing in milliseconds
        - config_used: A dictionary containing the configuration parameters 
            used for the query processing
    """
    query: str
    prompt_used: str
    retrieved_chunks: list[RetrievedChunk]
    final_context: str
    generated_answer: str
    timings_ms: dict
    config_used: dict
