from __future__ import annotations

import httpx

from app.core.config import Settings


class GeminiClient:
    def __init__(self, settings: Settings) -> None:
        self.settings = settings
        self.timeout = settings.http_timeout_seconds

    async def is_available(self) -> bool:
        if self.settings.use_mock_providers:
            return True
        return bool(self.settings.gemini_api_key)

    async def generate(
        self,
        system_prompt: str,
        user_prompt: str,
        temperature: float,
        max_output_tokens: int,
    ) -> str:
        if self.settings.use_mock_providers:
            return self._mock_generate(user_prompt)

        if not self.settings.gemini_api_key:
            raise ValueError("GEMINI_API_KEY is not configured")

        model = self.settings.gemini_model
        url = (
            f"https://generativelanguage.googleapis.com/v1beta/models/"
            f"{model}:generateContent?key={self.settings.gemini_api_key}"
        )

        payload = {
            "system_instruction": {
                "parts": [{"text": system_prompt}]
            },
            "contents": [
                {
                    "role": "user",
                    "parts": [{"text": user_prompt}]
                }
            ],
            "generationConfig": {
                "temperature": temperature,
                "maxOutputTokens": max_output_tokens,
            },
        }

        async with httpx.AsyncClient(timeout=self.timeout) as client:
            response = await client.post(url, json=payload)
            response.raise_for_status()
            data = response.json()

        candidates = data.get("candidates", [])
        if not candidates:
            return "No response generated by Gemini."

        parts = candidates[0].get("content", {}).get("parts", [])
        texts = [p.get("text", "") for p in parts if "text" in p]
        return "\n".join(texts).strip()

    def _mock_generate(self, user_prompt: str) -> str:
        if "Insufficient grounded context" in user_prompt:
            return "Insufficient grounded context to provide a reliable answer."
        return (
            "According to the retrieved context, open circuit defects are associated with "
            "interruptions in the intended conductive path of the printed board."
        )
